name: Test

on:
  push:
    branches:
      - "master"
    paths:
      - "patches/**/*.patch"
      - "ss2/pom.xml"
      - "*.sh"
      - "!COPYING"
      - "!README.md"
      - "!.gitignore"
  pull_request:
    branches:
      - "master"
    paths:
      - "patches/**/*.patch"
      - "ss2/pom.xml"
      - "*.sh"
      - "!COPYING"
      - "!README.md"
      - "!.gitignore"
  workflow_dispatch:


jobs:
  build:
    timeout-minutes: 2
    strategy:
      fail-fast: false
      matrix:
        java-version: [8, 11, 17, 21, 25]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    name: Build on Java ${{ matrix.java-version }} (${{ matrix.os }})
    steps:
      - uses: actions/checkout@v6

      - uses: actions/cache@v5
        with:
          path: ./tmp
          key: java-${{ matrix.java-version }}-tmp-${{ github.repository }}-${{ hashFiles('patches/**/*.patch') }}
          restore-keys: |
            java-${{ matrix.java-version }}-

      - uses: actions/setup-java@v5
        with:
          distribution: corretto
          java-version: ${{ matrix.java-version }}
          cache: maven

      - name: Build
        run: |
          rm -rf tmp
          ls -alh
          ./build.sh
