name: Test

on:
  push:
    branches:
      - "master"
    paths:
      - "patches/**/*.patch"
      - "ss2/pom.xml"
      - "*.sh"
      - "!COPYING"
      - "!README.md"
      - "!.gitignore"
  pull_request:
    branches:
      - "master"
    paths:
      - "patches/**/*.patch"
      - "ss2/pom.xml"
      - "*.sh"
      - "!COPYING"
      - "!README.md"
      - "!.gitignore"
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    strategy:
      fail-fast: false
      matrix:
        java-version: [8, 11, 17, 21, 25]

    name: Build on Java ${{ matrix.java-version }}
    steps:
      - uses: actions/checkout@v6

      - uses: actions/cache@v5
        with:
          path: ./tmp
          key: java-${{ matrix.java-version }}-tmp-${{ github.repository }}-${{ hashFiles('patches/**/*.patch') }}
          restore-keys: |
            java-${{ matrix.java-version }}-

      - uses: actions/setup-java@v5
        with:
          distribution: corretto
          java-version: ${{ matrix.java-version }}
          cache: maven

      - run: ./build.sh
